import java.io.File
import java.lang.Exception

// Exports wordlist into HTML file


fun saveToHTMLfile(data_full: List<Word>, pathfile_: String): String {
    // saves the list of words into a html-format file
    if(data_full.isEmpty()) return "Nothing"
    if("." !in pathfile_) return "Wrong filename"
    val SPLIT_SIZE = 3500
    val times = data_full.size/SPLIT_SIZE+1
    if(times>1) print("[$times]")
    val chunk_size = data_full.size/times+1
    var current_part=0
    var return_status = "OK"
    data_full.sortedBy{it.w.uppercase()}.chunked(chunk_size) {data->
        current_part++
        try {
            val added_part_number = if(times>1) "$current_part" else ""
            val pathfile = pathfile_.dropLastWhile{it!='.'}.dropLast(1) + "$added_part_number." + pathfile_.takeLastWhile{it!='.'}
            val the_file = File(pathfile)
            if(the_file.exists()) the_file.delete()
            the_file.printWriter().use {out->
                out.println(head)
                data.forEach {word->
                    val mp3file = wordToFilename(word.w, ".mp3")
                    val picfile = wordToFilename(word.w, ".jpeg")
                    val line = "<tr><th>${word.w}</th> \n" +
                            "\t<th><audio controls><source src=\"..\\mp3\\$mp3file\"></auio></th> \n" +
                            "\t<th><img src=\"..\\pic\\$picfile\"></img></th> \n" +
                            "\t<th class=t>${word.t}</th><th class=e>\n" +
                            "\t<th class=e>${word.f}</th>\n</tr>"
                    out.println(line)
                }
                out.println(tail)
            }
        } catch (ex: Exception) {
            println("ERROR " + ex.message)
            return_status = "ERROR"
        }
    }
    return return_status
}
private val head = """
<!DOCTYPE html>
<html>
  <head>
	<style>
		body {text-align: left;}
		th {padding-right:25px;font-size:22px;color:blue;font-style:normal}
		th.t {font-size:22px;color:black;font-style:normal}
		th.e {font-size:18px;color:black;font-style:italic}
		table {border-collapse:collapse;}
		tr {border-top:1px solid gainsboro;border-bottom:1px solid gainsboro;}
		audio {display:block;height:30px;width:110px}
        img {width:110px}
	</style>
    <meta charset="utf-8">
    <title>LingQ words</title>
  </head>
  <body>
	<table>
        """
private val tail = """
	</table>
  </body>
</html>
    <!--- Generated by LingQWordsExport application. --->
   """
